name: checks

on: [pull_request]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
